defmodule StateOfElixir.Languages do
  # TODO This list needs to be normalised
  @languages [
    "Abkhazian",
    "Achinese",
    "Acoli",
    "Adangme",
    "Adyghe",
    "Afar",
    "Afrihili",
    "Afrikaans",
    "Aghem",
    "Ainu",
    "Akan",
    "Akkadian",
    "Akoose",
    "Alabama",
    "Albanian",
    "Aleut",
    "Algerian Arabic",
    "Amarik",
    "American English",
    "American Sign Language",
    "Ancient Egyptian",
    "Ancient Greek",
    "Angika",
    "Ao Naga",
    "Arabik",
    "Aragonese",
    "Aramaic",
    "Araona",
    "Arapaho",
    "Arawak",
    "Armenian",
    "Aromanian",
    "Arpitan",
    "Assamese",
    "Asturian",
    "Asu",
    "Atsam",
    "Australian English",
    "Austrian German",
    "Avaric",
    "Avestan",
    "Awadhi",
    "Aymara",
    "Azerbaijani",
    "Badaga",
    "Bafia",
    "Bafut",
    "Bakhtiari",
    "Balinese",
    "Baluchi",
    "Bambara",
    "Bamun",
    "Banjar",
    "Basaa",
    "Bashkir",
    "Basque",
    "Batak Toba",
    "Bavarian",
    "Beja",
    "Belarus kasa",
    "Bemba",
    "Bena",
    "Bengali kasa",
    "Betawi",
    "Bɛɛmis kasa",
    "Bhojpuri",
    "Bikol",
    "Bini",
    "Bishnupriya",
    "Bislama",
    "Blin",
    "Blissymbols",
    "Bodo",
    "Borɔfo",
    "Bosnian",
    "Bɔlgeria kasa",
    "Brahui",
    "Braj",
    "Brazilian Portuguese",
    "Breton",
    "British English",
    "Buginese",
    "Bulu",
    "Buriat",
    "Caddo",
    "Cajun French",
    "Canadian English",
    "Canadian French",
    "Cantonese",
    "Capiznon",
    "Carib",
    "Catalan",
    "Cayuga",
    "Cebuano",
    "Central Atlas Tamazight",
    "Central Dusun",
    "Central Kurdish",
    "Central Yupik",
    "Chadian Arabic",
    "Chagatai",
    "Chamorro",
    "Chechen",
    "Cherokee",
    "Cheyenne",
    "Chibcha",
    "Chiga",
    "Chimborazo Highland Quichua",
    "Chinook Jargon",
    "Chipewyan",
    "Choctaw",
    "Church Slavic",
    "Chuukese",
    "Chuvash",
    "Classical Newari",
    "Classical Syriac",
    "Colognian",
    "Comorian",
    "Congo Swahili",
    "Coptic",
    "Cornish",
    "Corsican",
    "Cree",
    "Creek",
    "Crimean Turkish",
    "Croatian",
    "Dakota",
    "Danish",
    "Dargwa",
    "Dazaga",
    "Delaware",
    "Dɛɛkye",
    "Dinka",
    "Divehi",
    "Dogri",
    "Dogrib",
    "Duala",
    "Dyula",
    "Dzongkha",
    "Eastern Frisian",
    "Efik",
    "Egyptian Arabic",
    "Ekajuk",
    "Elamite",
    "Embu",
    "Emilian",
    "Erzya",
    "Esperanto",
    "Estonian",
    "European Portuguese",
    "European Spanish",
    "Ewe",
    "Ewondo",
    "Extremaduran",
    "Fang",
    "Fanti",
    "Faroese",
    "Fiji Hindi",
    "Fijian",
    "Filipino",
    "Finnish",
    "Flemish",
    "Fon",
    "Frafra",
    "Frɛnkye",
    "Friulian",
    "Fulah",
    "Ga",
    "Gagauz",
    "Galician",
    "Gan Chinese",
    "Ganda",
    "Gayo",
    "Gbaya",
    "Geez",
    "Georgian",
    "Gheg Albanian",
    "Ghomala",
    "Gilaki",
    "Gilbertese",
    "Goan Konkani",
    "Gondi",
    "Gorontalo",
    "Gothic",
    "Grebo",
    "Greek kasa",
    "Guarani",
    "Gujarati",
    "Gusii",
    "Gwichʼin",
    "Gyaaman",
    "Gyabanis kasa",
    "Gyapan kasa",
    "Haida",
    "Haitian",
    "Hakka Chinese",
    "Hangri kasa",
    "Hausa",
    "Hawaiian",
    "Hebrew",
    "Herero",
    "Hiligaynon",
    "Hindi",
    "Hiri Motu",
    "Hittite",
    "Hmong",
    "Hupa",
    "Iban",
    "Ibibio",
    "Icelandic",
    "Ido",
    "Igbo",
    "Iloko",
    "Inari Sami",
    "Indonihyia kasa",
    "Ingrian",
    "Ingush",
    "Interlingua",
    "Interlingue",
    "Inuktitut",
    "Inupiaq",
    "Irish",
    "Italy kasa",
    "Jamaican Creole English",
    "Jju",
    "Jola-Fonyi",
    "Judeo-Arabic",
    "Judeo-Persian",
    "Jutish",
    "Kabardian",
    "Kabuverdianu",
    "Kabyle",
    "Kachin",
    "Kaingang",
    "Kako",
    "Kalaallisut",
    "Kalenjin",
    "Kalmyk",
    "Kamba",
    "Kambodia kasa",
    "Kanembu",
    "Kannada",
    "Kanuri",
    "Kara-Kalpak",
    "Karachay-Balkar",
    "Karelian",
    "Kashmiri",
    "Kashubian",
    "Kawi",
    "Kazakh",
    "Kenyang",
    "Khasi",
    "Khotanese",
    "Khowar",
    "Kikuyu",
    "Kimbundu",
    "Kinaray-a",
    "Kirmanjki",
    "Klingon",
    "Kom",
    "Komi",
    "Komi-Permyak",
    "Kongo",
    "Konkani",
    "Korea kasa",
    "Koro",
    "Kosraean",
    "Kotava",
    "Koyra Chiini",
    "Koyraboro Senni",
    "Kpelle",
    "Krio",
    "Kuanyama",
    "Kumyk",
    "Kurdish",
    "Kurukh",
    "Kutenai",
    "Kwasio",
    "Kyaena kasa",
    "Kyɛk kasa",
    "Kyrgyz",
    "Kʼicheʼ",
    "Ladino",
    "Lahnda",
    "Lakota",
    "Lamba",
    "Langi",
    "Lao",
    "Latgalian",
    "Latin",
    "Latin American Spanish",
    "Latvian",
    "Laz",
    "Lezghian",
    "Ligurian",
    "Limburgish",
    "Lingala",
    "Lingua Franca Nova",
    "Literary Chinese",
    "Lithuanian",
    "Livonian",
    "Lojban",
    "Lombard",
    "Low German",
    "Lower Silesian",
    "Lower Sorbian",
    "Lozi",
    "Luba-Katanga",
    "Luba-Lulua",
    "Luiseno",
    "Lule Sami",
    "Lunda",
    "Luo",
    "Luxembourgish",
    "Luyia",
    "Maba",
    "Macedonian",
    "Machame",
    "Madurese",
    "Mafa",
    "Magahi",
    "Main-Franconian",
    "Maithili",
    "Makasar",
    "Makhuwa-Meetto",
    "Makonde",
    "Malagasy",
    "Malay kasa",
    "Malayalam",
    "Maltese",
    "Manchu",
    "Mandar",
    "Mandingo",
    "Manipuri",
    "Manx",
    "Maori",
    "Mapuche",
    "Marathi",
    "Mari",
    "Marshallese",
    "Marwari",
    "Masai",
    "Mazanderani",
    "Medumba",
    "Mende",
    "Mentawai",
    "Meru",
    "Metaʼ",
    "Mexican Spanish",
    "Micmac",
    "Middle Dutch",
    "Middle English",
    "Middle French",
    "Middle High German",
    "Middle Irish",
    "Min Nan Chinese",
    "Minangkabau",
    "Mingrelian",
    "Mirandese",
    "Mizo",
    "Modern Standard Arabic",
    "Mohawk",
    "Moksha",
    "Moldavian",
    "Mongo",
    "Mongolian",
    "Morisyen",
    "Moroccan Arabic",
    "Mossi",
    "Multiple Languages",
    "Mundang",
    "Muslim Tat",
    "Myene",
    "Nama",
    "Nauru",
    "Navajo",
    "Ndonga",
    "Neapolitan",
    "Newari",
    "Nɛpal kasa",
    "Ngambay",
    "Ngiemboon",
    "Ngomba",
    "Nheengatu",
    "Nias",
    "Niuean",
    "No linguistic content",
    "Nogai",
    "North Ndebele",
    "Northern Frisian",
    "Northern Sami",
    "Northern Sotho",
    "Norwegian",
    "Norwegian Bokmål",
    "Norwegian Nynorsk",
    "Novial",
    "Nuer",
    "Nyamwezi",
    "Nyanja",
    "Nyankole",
    "Nyasa Tonga",
    "Nyoro",
    "Nzima",
    "NʼKo",
    "Occitan",
    "Ojibwa",
    "Old English",
    "Old French",
    "Old High German",
    "Old Irish",
    "Old Norse",
    "Old Persian",
    "Old Provençal",
    "Oriya",
    "Oromo",
    "Osage",
    "Ossetic",
    "Ottoman Turkish",
    "Pahlavi",
    "Palatine German",
    "Palauan",
    "Pali",
    "Pampanga",
    "Pangasinan",
    "Papiamento",
    "Pashto",
    "Pennsylvania German",
    "Pɛɛhyia kasa",
    "Phoenician",
    "Picard",
    "Piedmontese",
    "Plautdietsch",
    "Pohnpeian",
    "Pontic",
    "Pɔland kasa",
    "Pɔɔtugal kasa",
    "Prussian",
    "Pungyabi kasa",
    "Quechua",
    "Rahyia kasa",
    "Rajasthani",
    "Rapanui",
    "Rarotongan",
    "Rewanda kasa",
    "Riffian",
    "Romagnol",
    "Romansh",
    "Romany",
    "Rombo",
    "Romenia kasa",
    "Root",
    "Rotuman",
    "Roviana",
    "Rundi",
    "Rusyn",
    "Rwa",
    "Saho",
    "Sakha",
    "Samaritan Aramaic",
    "Samburu",
    "Samoan",
    "Samogitian",
    "Sandawe",
    "Sango",
    "Sangu",
    "Sanskrit",
    "Santali",
    "Sardinian",
    "Sasak",
    "Sassarese Sardinian",
    "Saterland Frisian",
    "Saurashtra",
    "Scots",
    "Scottish Gaelic",
    "Selayar",
    "Selkup",
    "Sena",
    "Seneca",
    "Serbian",
    "Serbo-Croatian",
    "Serer",
    "Seri",
    "Shambala",
    "Shan",
    "Shona",
    "Sichuan Yi",
    "Sicilian",
    "Sidamo",
    "Siksika",
    "Silesian",
    "Simplified Chinese",
    "Sindhi",
    "Sinhala",
    "Skolt Sami",
    "Slave",
    "Slovak",
    "Slovenian",
    "Soga",
    "Sogdien",
    "Somalia kasa",
    "Soninke",
    "South Azerbaijani",
    "South Ndebele",
    "Southern Altai",
    "Southern Sami",
    "Southern Sotho",
    "Spain kasa",
    "Sranan Tongo",
    "Standard Moroccan Tamazight",
    "Sukuma",
    "Sumerian",
    "Sundanese",
    "Susu",
    "Swahili",
    "Swati",
    "Sweden kasa",
    "Swiss French",
    "Swiss German",
    "Swiss High German",
    "Syriac",
    "Tachelhit",
    "Taeland kasa",
    "Tagalog",
    "Tahitian",
    "Taita",
    "Tajik",
    "Talysh",
    "Tamashek",
    "Tamil kasa",
    "Taroko",
    "Tasawaq",
    "Tatar",
    "Telugu",
    "Tereno",
    "Teso",
    "Tetum",
    "Tɛɛki kasa",
    "Tibetan",
    "Tigre",
    "Tigrinya",
    "Timne",
    "Tiv",
    "Tlingit",
    "Tok Pisin",
    "Tokelau",
    "Tongan",
    "Tornedalen Finnish",
    "Traditional Chinese",
    "Tsakhur",
    "Tsakonian",
    "Tsimshian",
    "Tsonga",
    "Tswana",
    "Tulu",
    "Tumbuka",
    "Tunisian Arabic",
    "Turkmen",
    "Turoyo",
    "Tuvalu",
    "Tuvinian",
    "Twi",
    "Tyap",
    "Udmurt",
    "Ugaritic",
    "Ukren kasa",
    "Umbundu",
    "Unknown Language",
    "Upper Sorbian",
    "Urdu kasa",
    "Uyghur",
    "Uzbek",
    "Vai",
    "Venda",
    "Venetian",
    "Veps",
    "Viɛtnam kasa",
    "Volapük",
    "Võro",
    "Votic",
    "Vunjo",
    "Walloon",
    "Walser",
    "Waray",
    "Warlpiri",
    "Washo",
    "Wayuu",
    "Welsh",
    "West Flemish",
    "Western Frisian",
    "Western Mari",
    "Wolaytta",
    "Wolof",
    "Wu Chinese",
    "Xhosa",
    "Xiang Chinese",
    "Yangben",
    "Yao",
    "Yapese",
    "Yemba",
    "Yiddish",
    "Yoruba",
    "Zapotec",
    "Zarma",
    "Zaza",
    "Zeelandic",
    "Zenaga",
    "Zhuang",
    "Zoroastrian Dari",
    "Zulu",
    "Zuni"
  ]

  def languages, do: @languages
end
